### ISSUE TITLE
Topic name (CS-Viva_Prep.) is not sufficient to explain what to do , Please add the description..

### ISSUE THREAD

**Issue by viditvarshney** [DSC-Galgotias/CS-Viva_Prepration#1]
- Add the Description
- Like the topics--> Engineering Subjects viva preparation for externals , Data Structure Interview Questions etc

**Comment by honeycoder96** [comment]
hi @viditvarshney 
Thanks for your interest in contributing to the dsc organization.
This repository is quite old actually and is not currently maintained right now.
we will be deleting it very soon and add a web app repository for the same purpose.

watch out for the same :)
Thanking you.
